'use strict';
module.exports = function(sequelize, DataTypes) {
  var yxd_references = sequelize.define('yxd_references', {
    mac_id: DataTypes.STRING,
    lcircle_01_x:DataTypes.FLOAT,
    lcircle_01_y:DataTypes.FLOAT,
    lcircle_02_x:DataTypes.FLOAT,
    lcircle_02_y:DataTypes.FLOAT,
    lcircle_03_x:DataTypes.FLOAT,
    lcircle_03_y:DataTypes.FLOAT,
    lcircle_725_x:DataTypes.FLOAT,
    lcircle_725_y:DataTypes.FLOAT,
    lcircle_635_x:DataTypes.FLOAT,
    lcircle_635_y:DataTypes.FLOAT,
    lcircle_4101_x:DataTypes.FLOAT,
    lcircle_4101_y:DataTypes.FLOAT,
    lcircle_4102_x:DataTypes.FLOAT,
    lcircle_4102_y:DataTypes.FLOAT,
    lbreak_01_x:DataTypes.FLOAT,
    lbreak_01_y:DataTypes.FLOAT,
    lbreak_02_x:DataTypes.FLOAT,
    lbreak_02_y:DataTypes.FLOAT,
    lfoot_top:DataTypes.INTEGER,
    lfoot_bottom:DataTypes.INTEGER,
    lfoot_right:DataTypes.INTEGER,
    lfoot_left:DataTypes.INTEGER,
    lh_turn:DataTypes.INTEGER,
    lv_turn:DataTypes.INTEGER,
    lscale:DataTypes.FLOAT,
    lcircle_18_x:DataTypes.FLOAT,
    lcircle_18_y:DataTypes.FLOAT,
    lcircle_1801_x:DataTypes.FLOAT,
    lcircle_1801_y:DataTypes.FLOAT,
    lcircle_1802_x:DataTypes.FLOAT,
    lcircle_1802_y:DataTypes.FLOAT,
    lcircle_90_x:DataTypes.FLOAT,
    lcircle_90_y:DataTypes.FLOAT,
    lcircle_825_x:DataTypes.FLOAT,
    lcircle_825_y:DataTypes.FLOAT,
    lcircle_78_x:DataTypes.FLOAT,
    lcircle_78_y:DataTypes.FLOAT,
    lcircle_80_x:DataTypes.FLOAT,
    lcircle_80_y:DataTypes.FLOAT,
    lcircle_65_x:DataTypes.FLOAT,
    lcircle_65_y:DataTypes.FLOAT,
    rcircle_01_x:DataTypes.FLOAT,
    rcircle_01_y:DataTypes.FLOAT,
    rcircle_02_x:DataTypes.FLOAT,
    rcircle_02_y:DataTypes.FLOAT,
    rcircle_03_x:DataTypes.FLOAT,
    rcircle_03_y:DataTypes.FLOAT,
    rcircle_725_x:DataTypes.FLOAT,
    rcircle_725_y:DataTypes.FLOAT,
    rcircle_635_x:DataTypes.FLOAT,
    rcircle_635_y:DataTypes.FLOAT,
    rcircle_4101_x:DataTypes.FLOAT,
    rcircle_4101_y:DataTypes.FLOAT,
    rcircle_4102_x:DataTypes.FLOAT,
    rcircle_4102_y:DataTypes.FLOAT,
    rbreak_01_x:DataTypes.FLOAT,
    rbreak_01_y:DataTypes.FLOAT,
    rbreak_02_x:DataTypes.FLOAT,
    rbreak_02_y:DataTypes.FLOAT,
    rfoot_top:DataTypes.INTEGER,
    rfoot_bottom:DataTypes.INTEGER,
    rfoot_right:DataTypes.INTEGER,
    rfoot_left:DataTypes.INTEGER,
    rh_turn:DataTypes.INTEGER,
    rv_turn:DataTypes.INTEGER,
    rscale:DataTypes.FLOAT,
    rcircle_18_x:DataTypes.FLOAT,
    rcircle_18_y:DataTypes.FLOAT,
    rcircle_1801_x:DataTypes.FLOAT,
    rcircle_1801_y:DataTypes.FLOAT,
    rcircle_1802_x:DataTypes.FLOAT,
    rcircle_1802_y:DataTypes.FLOAT,
    rcircle_90_x:DataTypes.FLOAT,
    rcircle_90_y:DataTypes.FLOAT,
    rcircle_825_x:DataTypes.FLOAT,
    rcircle_825_y:DataTypes.FLOAT,
    rcircle_78_x:DataTypes.FLOAT,
    rcircle_78_y:DataTypes.FLOAT,
    rcircle_80_x:DataTypes.FLOAT,
    rcircle_80_y:DataTypes.FLOAT,
    rcircle_65_x:DataTypes.FLOAT,
    rcircle_65_y:DataTypes.FLOAT
  },{
       timestamps: false
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return yxd_references;
};